import Head from "next/head";
import Header from "../Commen/Header";
import Sidebar from "../Commen/Sidebar";
import FreelyHome from "./FreelyHome";
import Myprofile from "../Component/my-profile/Myprofile";
import Myaccount from "./Myaccount";
import styles from "../styles/Home.module.css";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
          
        />
      </Head>
     
      <Header />
      <FreelyHome/>
      {/* <Myaccount/> */}
    </div>
  );
}
